### ISSUE TITLE
Very basic functionality

### ISSUE THREAD

**Issue by Razpudding** [Zishrodrigues/real-time-web#1]
I doubt there's enough here to really understand how sockets work. This doesn't go beyond the basic socket.io example.

**Comment by Zishrodrigues** [comment]
Starting from zero experience with web sockets my main focus was on getting to know and understand what it means to use sockets and how to implement them in a basic yet functional way. The sockets.io chat example allowed me to do just that, giving me a digestible micro-project/tutorial to get a handle on things. The second thing I've focused on was figuring out how to get node.js projects on live environment.

All in all I think I've had an educational week and one which has given me a firm foundation to build on in the coming weeks. 

I'm currently figuring out how to use data in conjunction with sockets, but that's a story for another time!

**Comment by Zishrodrigues** [comment]
Added a features which transforms the chat app into an image guessing game as discussed last week. Live link coming soon.
